name: Build and Push Custom Zirconium OS

on:
  push:
    branches:
      - main
    paths:
      - 'Containerfile'
      - '.github/workflows/**'
  schedule:
    # Cron job to rebuild the whole image every Sunday at 00:00 for the newest securoty updates.
    - cron: '0 0 * * 0'
  workflow_dispatch: # in order to be able to manually initiate the action

env:
  REGISTRY: ghcr.io
  # Stores the image using the name of your repository
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (optioneel, voor multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in at GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate metadata (tags and lables)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and Push the OS Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          # Optimalisation for faster subsequent builds via GitHub cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
